### PR TITLE
Refactor recent emojis to store up to 18

### LINKED ISSUE #1: Modify the function that shows the emoji that the user recently used.
Modify the function that shows the emoji that the user recently used.
Currently, only one recently used emoji is saved in the program.
We want to modify so that up to 18 emojis can be stored.
Is your feature request related to a problem? Please describe.

### PR DESCRIPTION
**Pull request by jayeclark**
Signed-off-by: Jay Clark <jay@jayeclark.dev>

Fixes #1 

Hello! I came across this issue and was able to implement a fix. The 'recent emoji' section will now show up to 18 recently used unique emojis. As currently written, when you click on a recently used emoji to use it again, that emoji will move to the front of the list (i.e. most recently used.) I think this is the behavior that the extension _should_ have (it just makes a little less sense at the moment because the copy function & copy window is buggy), but if this isn't desired let me know and I can adjust the PR.

Screen Shot 2021-12-09 at 1 16 53 PM

### CODE REVIEW

**Comment by beyond58** [comment]
@jayeclark thank you so much!!

**Comment by beyond58** [comment]
After merge ForEach is not a function error occurred. I searched for this error and found that it was a similar arrangement ('Array-type-object') problem.  It's a link to what a similar arrangement is.
https://developer.mozilla.org/en-US/docs/Web/API/Element/getElementsByTagName

The solution is as follows.
Array.from (Array-type-object).forEach(
    function(element, index, array){ 
        // The code that I want to apply.
    }
);

After applying the solution it works well.

Thank you very much for spending time on my repo.

**Comment by jayeclark** [comment]
Hey, thanks. Is it line 123 that was the issue? I didn’t get any errors on my end and the array that forEach runs on  is just a simple array of strings. I’m familiar with needing to use Array.from() on array-like objects, but what it’s being applied to is just a regular array. 

I wonder if the problem is actually that on very first load the local storage is undefined?) That would explain why I didn’t get the error but you did (because once I started working I always had an array in local storage.) 

Anyway, sorry about that! I should have uninstalled and reloaded once I got everything working, to test if there were issues with initiation.

**Comment by beyond58** [comment]
@jayeclark 
Maybe i think It works well when there is data in local storage,  
Error occurs when first load (when there is no recent emoji data in local storage).

And the issue occurred in the underlined part.
image
image

You're welcome, you've been very helpful to me. :)

**Comment by jayeclark** [comment]
Ah, yep, makes total sense. Sorry for not catching that!

**Pull request merged**
